export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_CONTENT = "SET_CONTENT";
export const CLEAR_CONTENT = "CLEAR_CONTENT";

export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const CLEAR_ALL_PRODUCTS = "CLEAR_ALL_PRODUCTS";
export const CHANGE_PRODUCT_MESSAGE = "CHANGE_PRODUCT_MESSAGE";
export const CHANGE_FROM_CURRENT_WINDOW = "CHANGE_FROM_CURRENT_WINDOW";

export const SET_USER_PRODUCT_CART = "SET_USER_PRODUCT_CART";
export const CLEAR_ALL_USER_PRODUCT_CART = "CLEAR_ALL_USER_PRODUCT_CART";
